sudo: false
language: python
notifications:
  email: false
python:
  - pypy3
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install weakrefset; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then rm tests/test_examples.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then pip install lxml==3.4.4; fi
  - pip install -r rnd_requirements.txt
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
